#THIS Qt Project file is configured only for building on Linux and MacOS

QT += core gui widgets network

CONFIG += c++20

DEFINES -= QT_DISABLE_DEPRECATED_BEFORE=0x060000

INCLUDEPATH += $$PWD/src
INCLUDEPATH += $$PWD/include #for jsoncpp and sqlite3
INCLUDEPATH += $$PWD/include/json
INCLUDEPATH += $$PWD/include/sqlite3
INCLUDEPATH += $$DEPFOLDER/include

RC_FILE = QDento.rc
ICON = $$PWD/installer/macos/icon.icns

RESOURCES += \
    resources/Resource.qrc

TRANSLATIONS +=
    translations/Translation_fr_FR.ts
    translations/Translation_bg_BG.ts

HEADERS += \
    include/json/json-forwards.h \
    include/json/json.h \
    include/sqLite3/sqlite3.h \
    include/sqLite3/sqlite3ext.h \
    src/Database/Database.h \
    src/Database/DbAppointment.h \
    src/Database/DbBrowser.h \
    src/Database/DbCompany.h \
    src/Database/DbDentalVisit.h \
    src/Database/DbDentist.h \
    src/Database/DbDiagnosis.h \
    src/Database/DbInvoice.h \
    src/Database/DbNotes.h \
    src/Database/DbNotification.h \
    src/Database/DbPatient.h \
    src/Database/DbPatientSummary.h \
    src/Database/DbPerio.h \
    src/Database/DbProcedure.h \
    src/Database/DbUpdater.h \
    src/GlobalSettings.h \
    src/Model/CalendarStructs.h \
    src/Model/Date.h \
    src/Model/Dental/BridgeAlgorithms.h \
    src/Model/Dental/Dental.h \
    src/Model/Dental/DentalVisit.h \
    src/Model/Dental/Notification.h \
    src/Model/Dental/PerioStatistic.h \
    src/Model/Dental/PerioStatus.h \
    src/Model/Dental/PerioToothData.h \
    src/Model/Dental/Procedure.h \
    src/Model/Dental/ProcedureContainer.h \
    src/Model/Dental/ProcedureListElement.h \
    src/Model/Dental/Snapshot.h \
    src/Model/Dental/TimeFrame.h \
    src/Model/Dental/Tooth.h \
    src/Model/Dental/ToothContainer.h \
    src/Model/Dental/ToothIndex.h \
    src/Model/Dental/ToothUtils.h \
    src/Model/Financial/BusinessOperation.h \
    src/Model/Financial/FinancialEnums.h \
    src/Model/Financial/Invoice.h \
    src/Model/Financial/Issuer.h \
    src/Model/Financial/Recipient.h \
    src/Model/FreeFunctions.h \
    src/Model/NumenclatureTemplate.h \
    src/Model/Parser.h \
    src/Model/Patient.h \
    src/Model/PlainTable.h \
    src/Model/Settings.h \
    src/Model/TabType.h \
    src/Model/TableRows.h \
    src/Model/TableStructs.h \
    src/Model/Time.h \
    src/Model/User.h \
    src/Model/UserStructs.h \
    src/Model/Validators/AbstractValidator.h \
    src/Model/Validators/CommonValidators.h \
    src/Model/Validators/DateValidator.h \
    src/Model/Validators/FinancialValidator.h \
    src/Presenter/BrowserPresenter.h \
    src/Presenter/ButtonSurfaceMatrix.h \
    src/Presenter/CalendarPresenter.h \
    src/Presenter/CheckModel.h \
    src/Presenter/DetailedStatusPresenter.h \
    src/Presenter/DoctorDialogPresenter.h \
    src/Presenter/FinancialPresenter.h \
    src/Presenter/InputEnums.h \
    src/Presenter/LoginPresenter.h \
    src/Presenter/MainPresenter.h \
    src/Presenter/NewDocPresenter.h \
    src/Presenter/PatientDialogPresenter.h \
    src/Presenter/PatientHistoryPresenter.h \
    src/Presenter/PatientInfoPresenter.h \
    src/Presenter/PerioPresenter.h \
    src/Presenter/ProcedureCreator.h \
    src/Presenter/ProcedureDialogPresenter.h \
    src/Presenter/ProcedureEditorPresenter.h \
    src/Presenter/ProcedureListPresenter.h \
    src/Presenter/RecipientPresenter.h \
    src/Presenter/SettingsMainPresenter.h \
    src/Presenter/SurfacePanelPresenter.h \
    src/Presenter/TabInstance.h \
    src/Presenter/TabPresenter.h \
    src/Presenter/VisitPresenter.h \
    src/Resources.h \
    src/Version.h \
    src/View/CommonIcon.h \
    src/View/GlobalFunctions.h \
    src/View/Graphics/CPTooth.h \
    src/View/Graphics/CalendarViewData.h \
    src/View/Graphics/ControlPanelPolygon.h \
    src/View/Graphics/GraphicsView.h \
    src/View/Graphics/HexagonGraphicsItem.h \
    src/View/Graphics/PaintHint.h \
    src/View/Graphics/PerioChartItem.h \
    src/View/Graphics/PerioGraphicsButton.h \
    src/View/Graphics/PerioScene.h \
    src/View/Graphics/SelectionBox.h \
    src/View/Graphics/SpriteRect.h \
    src/View/Graphics/SpriteSheets.h \
    src/View/Graphics/TeethBuccalScene.h \
    src/View/Graphics/TeethLingualScene.h \
    src/View/Graphics/TeethViewScene.h \
    src/View/Graphics/ToothGraphicsItem.h \
    src/View/Graphics/ToothPainter.h \
    src/View/Graphics/ToothSprite.h \
    src/View/Graphics/Zodiac.h \
    src/View/Interfaces/AbstractComboBox.h \
    src/View/Interfaces/AbstractDateEdit.h \
    src/View/Interfaces/AbstractLabel.h \
    src/View/Interfaces/AbstractLineEdit.h \
    src/View/Interfaces/AbstractRangeEdit.h \
    src/View/Interfaces/AbstractSpinBox.h \
    src/View/Interfaces/AbstractSurfaceSelector.h \
    src/View/Interfaces/AbstractUIElement.h \
    src/View/ModalDialogBuilder.h \
    src/View/Printer.h \
    src/View/SubWidgets/ContextMenu.h \
    src/View/SubWidgets/ControlPanel.h \
    src/View/SubWidgets/DsnMenu.h \
    src/View/SubWidgets/PatientTileInfo.h \
    src/View/SubWidgets/PerioStatisticView.h \
    src/View/SubWidgets/PerioSummary.h \
    src/View/SubWidgets/ProcedureInput.h \
    src/View/SubWidgets/ProcedureListView.h \
    src/View/SubWidgets/SnapshotViewer.h \
    src/View/SubWidgets/SurfacePanel.h \
    src/View/SubWidgets/TabTitle.h \
    src/View/TableModels/BusinessOperationModel.h \
    src/View/TableModels/NameFilterProxyModel.h \
    src/View/TableModels/NotificationTableModel.h \
    src/View/TableModels/PlainTableModel.h \
    src/View/TableModels/ProcedureSelectModel.h \
    src/View/TableModels/ProcedureTableModel.h \
    src/View/TableModels/ProcedureTemplateModel.h \
    src/View/TableModels/QProcedure.h \
    src/View/Theme.h \
    src/View/Widgets/AboutDialog.h \
    src/View/Widgets/BrowserDialog.h \
    src/View/Widgets/BusinessOperationDialog.h \
    src/View/Widgets/ButtonDialog.h \
    src/View/Widgets/CalendarEventDialog.h \
    src/View/Widgets/CalendarView.h \
    src/View/Widgets/DetailedStatus.h \
    src/View/Widgets/DoctorSettingsDialog.h \
    src/View/Widgets/FinancialView.h \
    src/View/Widgets/GlobalWidgets.h \
    src/View/Widgets/InputDialog.h \
    src/View/Widgets/LoginView.h \
    src/View/Widgets/MultilineDialog.h \
    src/View/Widgets/NewDocDialog.h \
    src/View/Widgets/NotificationDialog.h \
    src/View/Widgets/NotificationListDialog.h \
    src/View/Widgets/PatientFormDialog.h \
    src/View/Widgets/PatientHistoryDialog.h \
    src/View/Widgets/PerioStatusView.h \
    src/View/Widgets/PerioView.h \
    src/View/Widgets/ProcedureDialog.h \
    src/View/Widgets/ProcedureEditDialog.h \
    src/View/Widgets/ProcedureElementDialog.h \
    src/View/Widgets/ProcedurePrintSelectDialog.h \
    src/View/Widgets/QDento.h \
    src/View/Widgets/RecipientEditView.h \
    src/View/Widgets/SaveDialog.h \
    src/View/Widgets/SettingsDialog.h \
    src/View/Widgets/SplashScreen.h \
    src/View/Widgets/TabView.h \
    src/View/Widgets/TableViewDialog.h \
    src/View/Widgets/ToothUi.h \
    src/View/Widgets/VisitView.h \
    src/View/Widgets/WelcomeWidget.h \
    src/View/uiComponents/AutoCompleteLineEdit.h \
    src/View/uiComponents/BigPushButton.h \
    src/View/uiComponents/CalendarTable.h \
    src/View/uiComponents/CalendarWidget.h \
    src/View/uiComponents/ColorPicker.h \
    src/View/uiComponents/ComboBox.h \
    src/View/uiComponents/CustomButton.h \
    src/View/uiComponents/CustomDateTimeEdit.h \
    src/View/uiComponents/DateEdit.h \
    src/View/uiComponents/FinancialTileButton.h \
    src/View/uiComponents/FurcationWidget.h \
    src/View/uiComponents/HalfRoundedButton.h \
    src/View/uiComponents/HoverButton.h \
    src/View/uiComponents/IconButton.h \
    src/View/uiComponents/LeadingZeroSpinBox.h \
    src/View/uiComponents/LineEdit.h \
    src/View/uiComponents/ListTable.h \
    src/View/uiComponents/MouseWheelGuard.h \
    src/View/uiComponents/NameEdit.h \
    src/View/uiComponents/NotesEdit.h \
    src/View/uiComponents/PerioButton.h \
    src/View/uiComponents/PerioSpinBox.h \
    src/View/uiComponents/PerioStateButton.h \
    src/View/uiComponents/PerioTable.h \
    src/View/uiComponents/PixmapLabel.h \
    src/View/uiComponents/RightClickButton.h \
    src/View/uiComponents/RoundedFrame.h \
    src/View/uiComponents/ShadowBakeWidget.h \
    src/View/uiComponents/ShortcutTile.h \
    src/View/uiComponents/SmoothWheelScroll.h \
    src/View/uiComponents/SpinBox.h \
    src/View/uiComponents/StatusButton.h \
    src/View/uiComponents/StatusMultiButton.h \
    src/View/uiComponents/TableView.h \
    src/View/uiComponents/TextBrowser.h \
    src/View/uiComponents/TextEdit.h \
    src/View/uiComponents/TileButton.h \
    src/View/uiComponents/ToothButton.h

SOURCES += \
    include/json/jsoncpp.cpp \
    include/sqLite3/sqlite3.c \
    src/Database/Database.cpp \
    src/Database/DbAppointment.cpp \
    src/Database/DbBrowser.cpp \
    src/Database/DbCompany.cpp \
    src/Database/DbDentalVisit.cpp \
    src/Database/DbDentist.cpp \
    src/Database/DbDiagnosis.cpp \
    src/Database/DbInvoice.cpp \
    src/Database/DbNotes.cpp \
    src/Database/DbNotification.cpp \
    src/Database/DbPatient.cpp \
    src/Database/DbPatientSummary.cpp \
    src/Database/DbPerio.cpp \
    src/Database/DbProcedure.cpp \
    src/Database/DbUpdater.cpp \
    src/GlobalSettings.cpp \
    src/Model/CalendarStructs.cpp \
    src/Model/Date.cpp \
    src/Model/Dental/PerioStatistic.cpp \
    src/Model/Dental/PerioToothData.cpp \
    src/Model/Dental/Procedure.cpp \
    src/Model/Dental/ProcedureContainer.cpp \
    src/Model/Dental/Snapshot.cpp \
    src/Model/Dental/TimeFrame.cpp \
    src/Model/Dental/Tooth.cpp \
    src/Model/Dental/ToothContainer.cpp \
    src/Model/Dental/ToothUtils.cpp \
    src/Model/Financial/BusinessOperation.cpp \
    src/Model/Financial/Invoice.cpp \
    src/Model/Financial/Issuer.cpp \
    src/Model/Financial/Recipient.cpp \
    src/Model/FreeFunctions.cpp \
    src/Model/Parser.cpp \
    src/Model/Patient.cpp \
    src/Model/PlainTable.cpp \
    src/Model/Time.cpp \
    src/Model/User.cpp \
    src/Model/Validators/CommonValidators.cpp \
    src/Model/Validators/DateValidator.cpp \
    src/Model/Validators/FinancialValidator.cpp \
    src/Presenter/BrowserPresenter.cpp \
    src/Presenter/ButtonSurfaceMatrix.cpp \
    src/Presenter/CalendarPresenter.cpp \
    src/Presenter/CheckModel.cpp \
    src/Presenter/DetailedStatusPresenter.cpp \
    src/Presenter/DoctorDialogPresenter.cpp \
    src/Presenter/FinancialPresenter.cpp \
    src/Presenter/LoginPresenter.cpp \
    src/Presenter/MainPresenter.cpp \
    src/Presenter/NewDocPresenter.cpp \
    src/Presenter/PatientDialogPresenter.cpp \
    src/Presenter/PatientHistoryPresenter.cpp \
    src/Presenter/PatientInfoPresenter.cpp \
    src/Presenter/PerioPresenter.cpp \
    src/Presenter/ProcedureCreator.cpp \
    src/Presenter/ProcedureDialogPresenter.cpp \
    src/Presenter/ProcedureEditorPresenter.cpp \
    src/Presenter/ProcedureListPresenter.cpp \
    src/Presenter/RecipientPresenter.cpp \
    src/Presenter/SettingsMainPresenter.cpp \
    src/Presenter/SurfacePanelPresenter.cpp \
    src/Presenter/TabInstance.cpp \
    src/Presenter/TabPresenter.cpp \
    src/Presenter/VisitPresenter.cpp \
    src/Resources.cpp \
    src/View/CommonIcon.cpp \
    src/View/GlobalFunctions.cpp \
    src/View/Graphics/CPTooth.cpp \
    src/View/Graphics/CalendarViewData.cpp \
    src/View/Graphics/ControlPanelPolygon.cpp \
    src/View/Graphics/GraphicsView.cpp \
    src/View/Graphics/HexagonGraphicsItem.cpp \
    src/View/Graphics/PaintHint.cpp \
    src/View/Graphics/PerioChartItem.cpp \
    src/View/Graphics/PerioGraphicsButton.cpp \
    src/View/Graphics/PerioScene.cpp \
    src/View/Graphics/SelectionBox.cpp \
    src/View/Graphics/SpriteRect.cpp \
    src/View/Graphics/SpriteSheets.cpp \
    src/View/Graphics/TeethBuccalScene.cpp \
    src/View/Graphics/TeethLingualScene.cpp \
    src/View/Graphics/TeethViewScene.cpp \
    src/View/Graphics/ToothGraphicsItem.cpp \
    src/View/Graphics/ToothPainter.cpp \
    src/View/Graphics/Zodiac.cpp \
    src/View/Interfaces/AbstractDateEdit.cpp \
    src/View/Interfaces/AbstractLineEdit.cpp \
    src/View/Interfaces/AbstractUIElement.cpp \
    src/View/ModalDialogBuilder.cpp \
    src/View/Printer.cpp \
    src/View/SubWidgets/ContextMenu.cpp \
    src/View/SubWidgets/ControlPanel.cpp \
    src/View/SubWidgets/DsnMenu.cpp \
    src/View/SubWidgets/PatientTileInfo.cpp \
    src/View/SubWidgets/PerioStatisticView.cpp \
    src/View/SubWidgets/PerioSummary.cpp \
    src/View/SubWidgets/ProcedureInput.cpp \
    src/View/SubWidgets/ProcedureListView.cpp \
    src/View/SubWidgets/SnapshotViewer.cpp \
    src/View/SubWidgets/SurfacePanel.cpp \
    src/View/SubWidgets/TabTitle.cpp \
    src/View/TableModels/BusinessOperationModel.cpp \
    src/View/TableModels/NameFilterProxyModel.cpp \
    src/View/TableModels/NotificationTableModel.cpp \
    src/View/TableModels/PlainTableModel.cpp \
    src/View/TableModels/ProcedureSelectModel.cpp \
    src/View/TableModels/ProcedureTableModel.cpp \
    src/View/TableModels/ProcedureTemplateModel.cpp \
    src/View/TableModels/QProcedure.cpp \
    src/View/Theme.cpp \
    src/View/Widgets/AboutDialog.cpp \
    src/View/Widgets/BrowserDialog.cpp \
    src/View/Widgets/BusinessOperationDialog.cpp \
    src/View/Widgets/ButtonDialog.cpp \
    src/View/Widgets/CalendarEventDialog.cpp \
    src/View/Widgets/CalendarView.cpp \
    src/View/Widgets/DetailedStatus.cpp \
    src/View/Widgets/DoctorSettingsDialog.cpp \
    src/View/Widgets/FinancialView.cpp \
    src/View/Widgets/InputDialog.cpp \
    src/View/Widgets/LoginView.cpp \
    src/View/Widgets/MultilineDialog.cpp \
    src/View/Widgets/NewDocDialog.cpp \
    src/View/Widgets/NotificationDialog.cpp \
    src/View/Widgets/NotificationListDialog.cpp \
    src/View/Widgets/PatientFormDialog.cpp \
    src/View/Widgets/PatientHistoryDialog.cpp \
    src/View/Widgets/PerioStatusView.cpp \
    src/View/Widgets/PerioView.cpp \
    src/View/Widgets/ProcedureDialog.cpp \
    src/View/Widgets/ProcedureEditDialog.cpp \
    src/View/Widgets/ProcedureElementDialog.cpp \
    src/View/Widgets/ProcedurePrintSelectDialog.cpp \
    src/View/Widgets/QDento.cpp \
    src/View/Widgets/RecipientEditView.cpp \
    src/View/Widgets/SaveDialog.cpp \
    src/View/Widgets/SettingsDialog.cpp \
    src/View/Widgets/SplashScreen.cpp \
    src/View/Widgets/TabView.cpp \
    src/View/Widgets/TableViewDialog.cpp \
    src/View/Widgets/VisitView.cpp \
    src/View/Widgets/WelcomeWidget.cpp \
    src/View/uiComponents/AutoCompleteLineEdit.cpp \
    src/View/uiComponents/BigPushButton.cpp \
    src/View/uiComponents/CalendarTable.cpp \
    src/View/uiComponents/CalendarWidget.cpp \
    src/View/uiComponents/ColorPicker.cpp \
    src/View/uiComponents/ComboBox.cpp \
    src/View/uiComponents/CustomButton.cpp \
    src/View/uiComponents/CustomDateTimeEdit.cpp \
    src/View/uiComponents/DateEdit.cpp \
    src/View/uiComponents/FinancialTileButton.cpp \
    src/View/uiComponents/FurcationWidget.cpp \
    src/View/uiComponents/HalfRoundedButton.cpp \
    src/View/uiComponents/HoverButton.cpp \
    src/View/uiComponents/IconButton.cpp \
    src/View/uiComponents/LeadingZeroSpinBox.cpp \
    src/View/uiComponents/LineEdit.cpp \
    src/View/uiComponents/ListTable.cpp \
    src/View/uiComponents/NameEdit.cpp \
    src/View/uiComponents/NotesEdit.cpp \
    src/View/uiComponents/PerioButton.cpp \
    src/View/uiComponents/PerioSpinBox.cpp \
    src/View/uiComponents/PerioStateButton.cpp \
    src/View/uiComponents/PerioTable.cpp \
    src/View/uiComponents/PixmapLabel.cpp \
    src/View/uiComponents/RightClickButton.cpp \
    src/View/uiComponents/RoundedFrame.cpp \
    src/View/uiComponents/ShadowBakeWidget.cpp \
    src/View/uiComponents/ShortcutTile.cpp \
    src/View/uiComponents/SmoothWheelScroll.cpp \
    src/View/uiComponents/SpinBox.cpp \
    src/View/uiComponents/StatusButton.cpp \
    src/View/uiComponents/StatusMultiButton.cpp \
    src/View/uiComponents/TableView.cpp \
    src/View/uiComponents/TextBrowser.cpp \
    src/View/uiComponents/TextEdit.cpp \
    src/View/uiComponents/TileButton.cpp \
    src/View/uiComponents/ToothButton.cpp \
    src/main.cpp

FORMS += \
    src/View/SubWidgets/ControlPanel.ui \
    src/View/SubWidgets/PatientTileInfo.ui \
    src/View/SubWidgets/PerioStatisticView.ui \
    src/View/SubWidgets/PerioSummary.ui \
    src/View/SubWidgets/ProcedureInput.ui \
    src/View/SubWidgets/ProcedureListView.ui \
    src/View/SubWidgets/SnapshotViewer.ui \
    src/View/SubWidgets/SurfacePanel.ui \
    src/View/SubWidgets/TabTitle.ui \
    src/View/Widgets/AboutDialog.ui \
    src/View/Widgets/BrowserDialog.ui \
    src/View/Widgets/BusinessOperationDialog.ui \
    src/View/Widgets/ButtonDialog.ui \
    src/View/Widgets/CalendarEventDialog.ui \
    src/View/Widgets/CalendarView.ui \
    src/View/Widgets/DetailedStatus.ui \
    src/View/Widgets/DoctorSettingsDialog.ui \
    src/View/Widgets/FinancialView.ui \
    src/View/Widgets/InputDialog.ui \
    src/View/Widgets/LoginView.ui \
    src/View/Widgets/MultilineDialog.ui \
    src/View/Widgets/NewDocDialog.ui \
    src/View/Widgets/NotificationDialog.ui \
    src/View/Widgets/NotificationListDialog.ui \
    src/View/Widgets/PatientFormDialog.ui \
    src/View/Widgets/PatientHistoryDialog.ui \
    src/View/Widgets/PerioStatusView.ui \
    src/View/Widgets/PerioView.ui \
    src/View/Widgets/ProcedureDialog.ui \
    src/View/Widgets/ProcedureEditDialog.ui \
    src/View/Widgets/ProcedureElementDialog.ui \
    src/View/Widgets/ProcedurePrintSelectDialog.ui \
    src/View/Widgets/QDento.ui \
    src/View/Widgets/RecipientEditView.ui \
    src/View/Widgets/SettingsDialog.ui \
    src/View/Widgets/TabView.ui \
    src/View/Widgets/TableViewDialog.ui \
    src/View/Widgets/VisitView.ui \
    src/View/Widgets/WelcomeWidget.ui


